jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:jSYPHNfO4E3S9ZIyfzO3+F2tTVnNGkJLG7roFJ73R9DZ1x8XmSOyA69DDzZC532u8k1s/X93v7VbmOwKXw==,iv:9yjcmNBnd5jICiAU1iRqvBIm+ecEkqYIMDJlw1LKWcY=,tag:kxojXN++TpKQPupOtozRjw==,type:str]
jupyterhub:
  hub:
    config:
      SharedPasswordAuthenticator:
        user_password: ENC[AES256_GCM,data:yi+H0x4zgw==,iv:VkIrXAYnVcRaSRyN+ubRTXNJ6qBBW6dK8N1rDW81t0U=,tag:KbgylPmJOQaO2Lbwfo9szg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2025-01-09T15:19:55Z'
    enc: CiUA4OM7eGez8KDuQZXma3aE2ZS9b3HenoeE9zJDAt9k+DMfqFVMEkkAnGhyNvSoFbF+zxcX/4id6Slvrld7haauv8LWoKhnKNroAKcT7U9aEqy80YJrXAMKJeuaWBgcTZUtpulxNqhb5FltsbNX8eY1
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-04-27T20:27:37Z'
  mac: ENC[AES256_GCM,data:AVffSdl7lrBcIL8fHdZs0PcAMjDk/TbFmGaZFkNCjNkWglDSpkiYeV1YAFUETKQ7lHJTJvRJkhb8VB6kCuPXf+N9g4JgDwplJHyxHvwFGlQQRho6gl+u3CJhFE45GTyGHS6ACautJp77/C6FjYAXRB8x6xe5MJVRUsLBAHWo/QA=,iv:UHz5fqfiThOBnCTYfyLVNNmykRDCrE0MFtt1BM6xvCo=,tag:0pwC0bAXRMxNCU4taatf1A==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.11.0
