basehub:
  jupyterhub:
    hub:
      config:
        SharedPasswordAuthenticator:
          user_password: ENC[AES256_GCM,data:wEGow8B/3J2lwqqmEywIOZI3NxgcIBA8+GLkNs6URA+xo+ZNZIQ=,iv:Ftz4PKOaTcHQwiVPbi95dwsCSt7kMg1Ih3wvvXQnK58=,tag:IU85YP5P1NQRfqAwFB7qGA==,type:str]
sops:
  kms: []
  gcp_kms:
    - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
      created_at: "2025-05-07T08:07:12Z"
      enc: CiUA4OM7eIHDivZcDvslLg3elkX0T4pYR0gVADUKsPLIdE9tM0IOEkkAWOWv8DPVHy3QKWEx9fdZ4KRPWJMSG8CKO+gfeqYiy+AOSoLZZpF4r3PXiCOkQIImX3yZbe2IrxHN0asSXzsJop8A2JMaTAkn
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2026-04-27T20:26:04Z"
  mac: ENC[AES256_GCM,data:p6QBjXJ7y7OdQZPWk0coVlHeatB7bm1Zz0cOWPiA8MRtvqT2dBN5MBwaqvWKCF3kQkvnVOOLtSvA9tdCb9U6io9tku7X3JM9ZZ6RYL3qQjzCDjkwiyINxrGr5Fk4Zh7sFUiuE7ZzP20iagYCUgPnMSjmcuIptxEJS9msNozA83A=,iv:Wq8XcceqvAGq2gsgYteMe8RPYmsAwwzTj2UmXMfGbUE=,tag:I7cKPgS//n1RErdj2/vN7Q==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.11.0
