basehub:
  jupyterhub:
    hub:
      config:
        SharedPasswordAuthenticator:
          user_password: ENC[AES256_GCM,data:mSkc0AQ0FA==,iv:sey+5Maz97nEBxg+hVW3rzMrmW87wi12H5vqjUOyxU8=,tag:Q4NWaCtucuHjUnO6Pfn7/Q==,type:str]
sops:
  kms: []
  gcp_kms:
    - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
      created_at: "2025-08-07T13:17:08Z"
      enc: CiUA4OM7eK/VsLTEtsrCh8V+s/m56JPwDsKI3mIE2+sMDVgsZRstEkkAXpa10DqAg6p8ZMfa5mZpJHr9S+C7Nj3FEh1eb5d0a1jju6HzcHi01x0rLTa2DB2b5sVthiKLT5l4SpkKBW0iPAwl3rXOBmNB
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2026-04-27T20:28:11Z"
  mac: ENC[AES256_GCM,data:Fezw2Bf9H8astP5Edpv+yllHKzeClkiJsHHypAI7Zy36BTWPhByGctWGXeCXOZICW13IK+QdWIsvTFY4fYBCnulmF0Y1AstUlBbUeakk1I6Nd4aFxsrfMWzvCdGlPNAsXop3FZuwMLwQV+/bMjY3tMNka4Z4uDc8CV8TeMgfHCM=,iv:w3KWSbxiU6qxPYsO/xWqa8QZ8ncNMhL8PnAgXTVDHsg=,tag:IvWhgIDn+HKA/WkQzismnw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.10.2
